application: briangray-nerdrock
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /index.html
  static_files: index.html
  upload: index\.html

- url: /redirect
  static_files: redirect.html
  upload: redirect\.html

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /browserconfig\.xml
  static_files: browserconfig.xml
  upload: browserconfig\.xml

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /blog.*
  script: nerdrock.wordpress

- url: /bcapi.*
  script: nerdrock.bandcampAPI

- url: /bc.*
  script: nerdrock.bandcamp

- url: /github.*
  script: nerdrock.github

- url: /proxy.*
  script: proxy.proxy

libraries:
- name: webapp2
  version: "2.5.2"
